### ISSUE TITLE
So cool!

### ISSUE THREAD

**Issue by csabal** [chasecee/pi-kiosk-scripts#1]
Hi,

Going to test this soon!!!!

Does it support any kind of virtual keyboard? Maybe this one: https://github.com/Linkek/keyboardTriggerServer 
Or any others through chromium addon? 

Also, could you integrate a /boot section, when we can include the wpa config for the wifi?

**Comment by chasecee** [comment]
My availability to help this project is limited due to work and family factors. Since this is pretty bare bones, you are welcome to fork and customize, sorry I'm not more helpful.
